### ISSUE TITLE
brew install sunshine error on macOS Ventura

### ISSUE THREAD

**Issue by ZhaoJunnNie** [LizardByte/homebrew-homebrew#11] opened 2024-05-10 09:29 UTC
### Describe the Bug

HEAD is now at 8b21db6 Merge pull request #2388 from LizardByte/nightly
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DSUNSHINE_ASSETS_DIR=sunshine/assets -DS
Last 15 lines from /Users/tou/Library/Logs/Homebrew/sunshine/01.cmake:
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc

CMake Error at cmake/targets/common.cmake:4 (add_executable):
  No SOURCES given to target: sunshine
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)

CMake Error at tests/CMakeLists.txt:107 (add_executable):
  No SOURCES given to target: test_sunshine

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by ReenigneArcher** [comment] 2024-05-10 11:41
This is a duplicate of https://github.com/LizardByte/Sunshine/issues/2369

**Closed by ReenigneArcher** 2024-05-10 11:41 UTC
